# Generated by Django 4.2.8 on 2025-07-06 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scan_images/')),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('allergy_type', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('treatment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scan History',
                'ordering': ['-scan_date'],
            },
        ),
    ]
